TREASURE_CARDS = {
    'weapons':
    [
        {
            'name': 'Maza Suiza Multiusos',
            'bonus': 4,
            'size': 2,
            'value': 600,
            'used_by': 'Human',
        },
        {
            'name': 'Arco con Lazitos',
            'bonus': 4,
            'size': 2,
            'value': 800,
            'used_by': 'Elf',
        },
        {
            'name': 'Baculo de Napalm',
            'bonus': 5,
            'size': 1,
            'value': 800,
            'used_by': 'Wizard',
        },
        {
            'name': 'Daga Traicionera',
            'bonus': 3,
            'size': 1,
            'value': 400,
            'used_by': 'Thief',
        },
        {
            'name': 'El broquel del Doncel',
            'bonus': 2,
            'size': 1,
            'value': 400,
            'used_by': 'all',
        },
    ],
    'armor':
    [
        {
            'name': 'Armadura de cuero',
            'bonus': 1,
            'value': 200,
            'part': 'Armadura',
            'used_by': 'Female',
        },
        {
            'name': 'Armadura de cuero',
            'bonus': 1,
            'value': 200,
            'part': 'Armadura',
            'used_by': 'Male',
        },
        {
            'name': 'Armadura de mithril',
            'bonus': 3,
            'value': 600,
            'part': 'Grande armadura',
            'used_by': 'Wizard',
        },
        {
            'name': 'Armadura llameante',
            'bonus': 3,
            'value': 400,
            'part': 'Armadura',
            'used_by': 'all',
        },
        {
            'name': 'Armadura pegajosa',
            'bonus': 1,
            'value': 200,
            'part': 'Armadura',
            'used_by': 'all',
        },
    ],
    'single_use':
    [
        {
            'name': 'Matar al escudero',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'value': None,
            'is_level_up': True,
        },
        {
            'name': 'Globitos de colores',
            'bonus': 5,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': False,
            'value': None,
        },
        {
            'name': 'Agua mineral',
            'bonus': 2,
            'group_effect': False,
            'used_by': 'Elf',
            'is_level_up': False,
            'value': 100,
        },
        {
            'name': 'Bebida deportiva sabor repugnante',
            'bonus': 2,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 200,
        },
        {
            'name': 'Cocion de ponfusion',
            'bonus': 3,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 100,
        },
        {
            'name': 'Conveniente error de la suma',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Doppelganger',
            'bonus': 5,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': False,
            'value': 300,
        },
        {
            'name': 'Invocar reglas de ingnotas',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Llorale al master',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Masacre de Hormigas',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Misil magico',
            'bonus': 5,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 300,
        },
        {
            'name': 'Mutilar cadaveres',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Pocion congelante explosiva',
            'bonus': 3,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 100,
        },
        {
            'name': 'Pocion de acido electroradioactivo',
            'bonus': 5,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 200,
        },
    ]
}
