TREASURE_CARDS = {
    'weapons':
    [
        {
            'name': 'Maza Suiza Multiusos',
            'bonus': 4,
            'cant_hands': 2,
            'value': 600,
            'used_by': 'Human',
            'is_big': True,
        },
        {
            'name': 'Arco con Lazitos',
            'bonus': 4,
            'cant_hands': 2,
            'value': 800,
            'used_by': 'Elf',
        },
        {
            'name': 'Baculo de Napalm',
            'bonus': 5,
            'cant_hands': 1,
            'value': 800,
            'used_by': 'Wizard',
        },
        {
            'name': 'Daga Traicionera',
            'bonus': 3,
            'cant_hands': 1,
            'value': 400,
            'used_by': 'Thief',
        },
        {
            'name': 'El broquel del Doncel',
            'bonus': 2,
            'cant_hands': 1,
            'value': 400,
            'used_by': 'all',
        },
        {
            'name': 'Escudo de Ubicuidad',
            'bonus': 4,
            'cant_hands': 1,
            'value': 600,
            'used_by': 'Warrrior',
            'is_big': True,
        },
        {
            'name': 'Espada bastarda y traicionera',
            'bonus': 2,
            'cant_hands': 1,
            'value': 400,
            'used_by': 'all',
            'is_big': False,
        },
        {
            'name': 'Espada emasculadora',
            'bonus': 3,
            'cant_hands': 1,
            'value': 400,
            'used_by': 'Female',
            'is_big': False,
        },
        {
            'name': 'Espada y cantante',
            'bonus': 2,
            'cant_hands': 1,
            'value': 400,
            'used_by': 'No Thief',
            'is_big': False,
        },
        {
            'name': 'Estoque de la injusta ventaja',
            'bonus': 3,
            'cant_hands': 1,
            'value': 600,
            'used_by': 'Elf',
            'is_big': False,
        },
        {
            'name': 'Lanza desmesurada',
            'bonus': 1,
            'cant_hands': 2,
            'value': 200,
            'used_by': 'all',
            'is_big': False,
        },
        {
            'name': 'Martillo destroza rodillas',
            'bonus': 4,
            'cant_hands': 1,
            'value': 600,
            'used_by': 'Dwarf',
            'is_big': False,
        },
        {
            'name': 'Maza afilada',
            'bonus': 4,
            'cant_hands': 1,
            'value': 600,
            'used_by': 'Cleric',
            'is_big': False,
        },
        {
            'name': 'Motosierra de mutilacion sangrienta',
            'bonus': 3,
            'cant_hands': 2,
            'value': 600,
            'used_by': 'all',
            'is_big': True,
        },
        {
            'name': 'Porra de masculinidad sublimada',
            'bonus': 3,
            'cant_hands': 1,
            'value': 400,
            'used_by': 'Male',
            'is_big': False,
        },
        {
            'name': 'Rallador de queso de la paz',
            'bonus': 3,
            'cant_hands': 1,
            'value': 400,
            'used_by': 'Cleric',
            'is_big': False,
        },
        {
            'name': 'Roca enorme',
            'bonus': 3,
            'cant_hands': 2,
            'value': 0,
            'used_by': 'No Thief',
            'is_big': True,
        },

    ],
    'armor':
    [
        {
            'name': 'Armadura de cuero',
            'bonus': 1,
            'value': 200,
            'part': 'Armadura',
            'used_by': 'Female',
        },
        {
            'name': 'Armadura de cuero',
            'bonus': 1,
            'value': 200,
            'part': 'Armadura',
            'used_by': 'Male',
        },
        {
            'name': 'Armadura de mithril',
            'bonus': 3,
            'value': 600,
            'part': 'Grande armadura',
            'used_by': 'Wizard',
        },
        {
            'name': 'Armadura llameante',
            'bonus': 3,
            'value': 400,
            'part': 'Armadura',
            'used_by': 'all',
        },
        {
            'name': 'Armadura pegajosa',
            'bonus': 1,
            'value': 200,
            'part': 'Armadura',
            'used_by': 'all',
        },
    ],
    'single_use':
    [
        {
            'name': 'Matar al escudero',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'value': None,
            'is_level_up': True,
        },
        {
            'name': 'Globitos de colores',
            'bonus': 5,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': False,
            'value': None,
        },
        {
            'name': 'Frasco de pegamento',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': False,
            'value': 100,
            'reroll_dice': True,

        },
        {
            'name': 'Agua mineral',
            'bonus': 2,
            'group_effect': False,
            'used_by': 'Elf',
            'is_level_up': False,
            'value': 100,
        },
        {
            'name': 'Bebida deportiva sabor repugnante',
            'bonus': 2,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 200,
        },
        {
            'name': 'Cocion de ponfusion',
            'bonus': 3,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 100,
        },
        {
            'name': 'Conveniente error de la suma',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Doppelganger',
            'bonus': 5,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': False,
            'value': 300,
        },
        {
            'name': 'Invocar reglas de ingnotas',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Llorale al master',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Masacre de Hormigas',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Misil magico',
            'bonus': 5,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 300,
        },
        {
            'name': 'Mutilar cadaveres',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': True,
            'value': None,
        },
        {
            'name': 'Pocion congelante explosiva',
            'bonus': 3,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 100,
        },
        {
            'name': 'Pocion de acido electroradioactivo',
            'bonus': 5,
            'group_effect': True,
            'used_by': 'all',
            'is_level_up': False,
            'value': 200,
        },
        {
            'name': 'Dado cargado',
            'bonus': None,
            'group_effect': False,
            'used_by': 'all',
            'is_level_up': False,
            'value': 300,
            'reroll_dice': True,
        },
    ]
}
